# Generated by Django 4.2.16 on 2024-11-05 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "default_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "default_postcode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "default_city",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "default_street_address1",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "default_street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "default_county",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "default_profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images"
                    ),
                ),
                (
                    "default_bio",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "default_location",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("default_birth_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
