# Generated by Django 4.2.16 on 2024-11-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="default_city",
            new_name="default_town_or_city",
        ),
    ]
