# Generated by Django 4.2.16 on 2024-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="placeholder", null=True, upload_to=""
            ),
        ),
    ]
