# Generated by Django 4.2.16 on 2024-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_order_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlineitem",
            name="product_size",
        ),
    ]
