# Generated by Django 4.2.17 on 2025-01-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField()),
                (
                    "has_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("on_sale", models.BooleanField(default=False)),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("men", "men"), ("women", "women")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("materials", models.TextField(blank=True, null=True)),
                ("country_origin", django_countries.fields.CountryField(max_length=2)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("review", models.TextField(blank=True, max_length=1500)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "men_shoe_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4", "Four"),
                            ("5", "Five"),
                            ("6", "Six"),
                            ("7", "Seven"),
                            ("8", "Eight"),
                            ("9", "Nine"),
                            ("10", "Ten"),
                            ("11", "Eleven"),
                            ("12", "Twelve"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "women_shoe_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4", "Four"),
                            ("5", "Five"),
                            ("6", "Six"),
                            ("7", "Seven"),
                            ("8", "Eight"),
                            ("9", "Nine"),
                            ("10", "Ten"),
                            ("11", "Eleven"),
                            ("12", "Twelve"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reviews",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="reviews_per_user"
            ),
        ),
    ]
