# Generated by Django 4.2.16 on 2024-10-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_measurement_measurement_type'),
    ]

    operations = [

        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to=''),
        ),
    ]
