# Generated by Django 4.2.16 on 2024-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_shippingday_shipping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percent',
            new_name='discount',
        ),
    ]
