# Generated by Django 4.2.16 on 2024-10-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_rename_discount_percent_product_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254, unique=True)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.subcategory",
            ),
        ),
    ]
