# Generated by Django 4.2.16 on 2024-10-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_subcategory_product_sub_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="friendly_name",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="id",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="image",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="slug",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="products.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_category",
                to="products.subcategory",
            ),
        ),
    ]
